paths:
  sfr79_dir: "/Users/foerster/Projects/SiGMo/data/SFR79_grids"   # read-in directory with SFR79 grids
  snp_dir_GMSsim: "/Users/foerster/Projects/SiGMo/outputs/_tmp/2022.11.28-11.50.58/gms_mhalo_population_1000gals_from_z2.0_to_z0_dt1e-03_wtd1_mhalo_sigma0.200_mstar6.0-9.0"
  plot_dir: "/Users/foerster/Projects/SiGMo/plots/_tmp/2022.11.28-11.50.58/gms_mhalo_population_1000gals_from_z2.0_to_z0_dt1e-03_wtd1_mhalo_sigma0.200_mstar6.0-9.0"   # plots base directory